### ISSUE TITLE
feat: there is no dedicated url for a result

### ISSUE THREAD

**Issue by Arif-un** [mdrubelamin2/pciu-cgpa-calculator#8]
every time a student need to fetch a result he/she needs to put ID every single time, even there is no dedicated URL to share the result.

solution:
ID in query params can be a solution and accessible from both side.

**Comment by mdrubelamin2** [comment]
That's a good idea, indeed. It was on my roadmap, thank you for pointing me about this feature. It will be integrated in the app soon.

**Comment by mdrubelamin2** [comment]
The feature is implemented on the app, thanks for the suggestion.

You will find a Share Button above the GPA table, by clicking it will copy the shareable link. ex: [https://pciu-result.vercel.app/CSE01906859](https://pciu-result.vercel.app/CSE01906859)

this page is server component, so it will fetch all results & calculate the CGPA during loading of the page.
